<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ShareefDell" failures="0" tests="1" name="testNGScript.Example6" time="1.051" errors="1" timestamp="26 Nov 2023 06:06:24 GMT" skipped="0">
  <testcase classname="testNGScript.Example6" name="method1" time="1.051">
    <error message="Method testNGScript.Example6.method1() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGScript.Example6.method1() didn't finish within the time-out 1000
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
at java.base@17.0.9/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.9/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- method1 -->
</testsuite> <!-- testNGScript.Example6 -->
